create_clock -period 10.000 -name adc4clk_p [get_ports adc4clk_p]

#############################  adc4  ##################################

set_property PACKAGE_PIN B17 [get_ports adc4clk_p]
set_property PACKAGE_PIN B18 [get_ports adc4clk_n]
set_property PACKAGE_PIN F13 [get_ports {adc4d_p[0]}]
set_property PACKAGE_PIN F14 [get_ports {adc4d_n[0]}]
set_property PACKAGE_PIN D14 [get_ports {adc4d_p[1]}]
set_property PACKAGE_PIN D15 [get_ports {adc4d_n[1]}]
set_property PACKAGE_PIN B20 [get_ports {adc4d_p[2]}]
set_property PACKAGE_PIN A20 [get_ports {adc4d_n[2]}]
set_property PACKAGE_PIN E16 [get_ports {adc4d_p[3]}]
set_property PACKAGE_PIN D16 [get_ports {adc4d_n[3]}]
set_property PACKAGE_PIN E13 [get_ports {adc4d_p[4]}]
set_property PACKAGE_PIN E14 [get_ports {adc4d_n[4]}]
set_property PACKAGE_PIN C13 [get_ports {adc4d_p[5]}]
set_property PACKAGE_PIN B13 [get_ports {adc4d_n[5]}]
set_property PACKAGE_PIN B21 [get_ports {adc4d_p[6]}]
set_property PACKAGE_PIN A21 [get_ports {adc4d_n[6]}]
set_property PACKAGE_PIN C22 [get_ports {adc4d_p[7]}]
set_property PACKAGE_PIN B22 [get_ports {adc4d_n[7]}]
set_property PACKAGE_PIN F16 [get_ports {adc4d_p[8]}]
set_property PACKAGE_PIN E17 [get_ports {adc4d_n[8]}]
set_property PACKAGE_PIN E22 [get_ports {adc4d_p[9]}]
set_property PACKAGE_PIN D22 [get_ports {adc4d_n[9]}]
set_property PACKAGE_PIN A18 [get_ports {adc4d_p[10]}]
set_property PACKAGE_PIN A19 [get_ports {adc4d_n[10]}]
set_property PACKAGE_PIN A13 [get_ports {adc4d_p[11]}]
set_property PACKAGE_PIN A14 [get_ports {adc4d_n[11]}]
set_property PACKAGE_PIN B15 [get_ports {adc4d_p[12]}]
set_property PACKAGE_PIN B16 [get_ports {adc4d_n[12]}]
set_property PACKAGE_PIN D20 [get_ports {adc4d_p[13]}]
set_property PACKAGE_PIN C20 [get_ports {adc4d_n[13]}]
set_property PACKAGE_PIN G21 [get_ports {adc4d_p[14]}]
set_property PACKAGE_PIN G22 [get_ports {adc4d_n[14]}]
set_property PACKAGE_PIN F19 [get_ports {adc4d_p[15]}]
set_property PACKAGE_PIN F20 [get_ports {adc4d_n[15]}]
set_property PACKAGE_PIN A15 [get_ports adc4of_p]
set_property PACKAGE_PIN A16 [get_ports adc4of_n]
set_property PACKAGE_PIN M5 [get_ports {adcshdn}]
set_property PACKAGE_PIN M6 [get_ports {adcdith}]
set_property PACKAGE_PIN K3 [get_ports {adcrand}]
set_property PACKAGE_PIN G3 [get_ports {adcpga}]


set_property IOSTANDARD LVDS_25 [get_ports adc4clk_*]
set_property IOSTANDARD LVDS_25 [get_ports {adc4d_p[*]}]
set_property IOSTANDARD LVDS_25 [get_ports {adc4d_n[*]}]
set_property IOSTANDARD LVCMOS25 [get_ports {adcshdn}]
set_property IOSTANDARD LVCMOS25 [get_ports {adcdith}]
set_property IOSTANDARD LVCMOS25 [get_ports {adcrand}]
set_property IOSTANDARD LVCMOS25 [get_ports {adcpga}]